from pathlib import Path
import json
p=Path('desktop/frontend/index.html')
s=p.read_text(encoding='utf-8')
s=s.replace('<title>LungScope v0.9.0 — Split GPU Inference</title>', '<title>LungScope Desktop v0.10.0 — Local Research Workstation</title>')
s=s.replace('v0.9.0 · AST-SAM + OPERA-CE · OPTIONAL CALIBRATED OPERA HEAD','v0.10.0 DESKTOP · LOCAL AST-SAM + OPERA-CE · OFFLINE AFTER SETUP')
s=s.replace('LungScope v0.9.0 separates general respiratory auscultation', 'LungScope Desktop v0.10.0 separates general respiratory auscultation')
s=s.replace('LUNGSCOPE v0.9.0 · RESEARCH PROTOTYPE · NOT A MEDICAL DEVICE · AST-SAM + OPERA-CE INFERENCE RUNS ON THE DEDICATED MODEL SERVICE · AST AND OPERA TASK HEADS REMAIN RESEARCH-ONLY; NO MODEL FUSION IS USED.', 'LUNGSCOPE DESKTOP v0.10.0 · RESEARCH PROTOTYPE · NOT A MEDICAL DEVICE · AST-SAM + OPERA-CE INFERENCE RUNS LOCALLY ON THIS WORKSTATION · AST AND OPERA TASK HEADS REMAIN RESEARCH-ONLY; NO MODEL FUSION IS USED.')
css='''.desktopbar{position:sticky;top:72px;z-index:9;border-bottom:1px solid var(--line);background:#071014f2;backdrop-filter:blur(12px);padding:8px 3vw;display:flex;align-items:center;gap:8px;flex-wrap:wrap}.desktopbar .desklabel{font:650 8px ui-monospace,monospace;letter-spacing:.13em;color:#5f757b;margin-right:2px}.deskstat{font:650 8px ui-monospace,monospace;letter-spacing:.09em;color:#789097;border:1px solid #1d3036;padding:7px 9px}.deskstat.ok{color:var(--mint);border-color:#31554f}.deskstat.warn{color:var(--amber);border-color:#5d4d2b}.deskstat.bad{color:var(--red);border-color:#5b3035}.desktopbar .spacer{flex:1}.deskbtn{border:1px solid #253a40;background:#081014;color:#94a8ac;padding:7px 10px;font:650 8px ui-monospace,monospace;letter-spacing:.09em;cursor:pointer}.deskbtn:hover{border-color:#31554f;color:var(--mint)}.deskbtn:disabled{opacity:.35;cursor:not-allowed}'''
s=s.replace('</style>',css+'\n</style>',1)
bar='''<div id="desktopBar" class="desktopbar hidden"><span class="desklabel">LOCAL COMPUTE</span><span id="deskRuntime" class="deskstat warn">RUNTIME CHECK</span><span id="deskEngine" class="deskstat warn">ENGINE OFFLINE</span><span id="deskGpu" class="deskstat">GPU · UNKNOWN</span><span id="deskHead" class="deskstat">OPERA HEAD · UNKNOWN</span><span class="spacer"></span><button id="deskInstall" class="deskbtn">INSTALL / REPAIR RUNTIME</button><button id="deskStart" class="deskbtn">START ENGINE</button><button id="deskStop" class="deskbtn">STOP ENGINE</button><button id="deskLogs" class="deskbtn">OPEN LOGS</button></div>'''
s=s.replace('</header>','</header>\n'+bar,1)
js=r'''const desktopHost={enabled:false,invoke:null,poll:null};
async function desktopInvoke(name,args={}){if(!desktopHost.invoke)throw new Error('Tauri desktop bridge unavailable');return desktopHost.invoke(name,args)}
function deskSet(id,text,kind=''){const n=$(id);if(!n)return;n.textContent=text;n.className='deskstat'+(kind?' '+kind:'')}
async function refreshDesktopHost(){if(!desktopHost.enabled)return;try{const s=await desktopInvoke('runtime_status');deskSet('deskRuntime',s.runtimeInstalled?'RUNTIME · INSTALLED':(s.installing?'RUNTIME · INSTALLING':'RUNTIME · NOT INSTALLED'),s.runtimeInstalled?'ok':(s.installing?'warn':'bad'));deskSet('deskEngine',s.engineReady?'ENGINE · READY':(s.engineRunning?'ENGINE · STARTING':'ENGINE · OFFLINE'),s.engineReady?'ok':(s.engineRunning?'warn':'bad'));deskSet('deskGpu',s.gpuName?`GPU · ${s.gpuName}`:(s.nvidiaAvailable?'GPU · NVIDIA DETECTED':'GPU · CPU / UNKNOWN'),s.nvidiaAvailable?'ok':'warn');$('deskInstall').disabled=!!s.installing;$('deskStart').disabled=!s.runtimeInstalled||!!s.engineRunning;$('deskStop').disabled=!s.engineRunning;if(s.engineReady){try{const r=await fetch('http://127.0.0.1:17842/v1/system/info',{cache:'no-store'});if(r.ok){const j=await r.json();deskSet('deskHead',`OPERA HEAD · ${(j.head_status||'UNKNOWN').toUpperCase()}`,j.head_status==='trained'?'ok':'warn');if(j.gpu?.name)deskSet('deskGpu',`GPU · ${j.gpu.name}`,'ok')}}catch{}}}catch(e){console.warn('desktop host status error',e);deskSet('deskEngine','DESKTOP BRIDGE ERROR','bad')}}
async function initDesktopHost(){const inv=window.__TAURI__?.core?.invoke;if(!inv)return;desktopHost.enabled=true;desktopHost.invoke=inv;$('desktopBar').classList.remove('hidden');$('deskInstall').onclick=async()=>{try{await desktopInvoke('install_runtime',{mode:'auto'});deskSet('deskRuntime','RUNTIME · INSTALLING','warn')}catch(e){deskSet('deskRuntime','INSTALL FAILED','bad');console.error(e)}await refreshDesktopHost()};$('deskStart').onclick=async()=>{try{await desktopInvoke('start_engine');deskSet('deskEngine','ENGINE · STARTING','warn');await new Promise(r=>setTimeout(r,1200));await restartModelWorker()}catch(e){deskSet('deskEngine','START FAILED','bad');console.error(e)}await refreshDesktopHost()};$('deskStop').onclick=async()=>{try{await desktopInvoke('stop_engine');stopModelWorker()}catch(e){console.error(e)}await refreshDesktopHost()};$('deskLogs').onclick=()=>desktopInvoke('open_logs').catch(console.error);await refreshDesktopHost();desktopHost.poll=setInterval(refreshDesktopHost,2500)}
void initDesktopHost();'''
marker="renderRespSites();draw($('respCanvas'),new Float32Array(500));"
assert marker in s, 'frontend initialization marker missing'
s=s.replace(marker,js+'\n'+marker,1)
p.write_text(s,encoding='utf-8')
Path('desktop/frontend/runtime_config_v090.json').write_text(json.dumps({'version':'0.10.0-desktop','apiBase':'http://127.0.0.1:17842','apiMode':'direct','requestTimeoutMs':420000,'architecture':'desktop-local-engine'},indent=2),encoding='utf-8')
print('desktop frontend patch PASS', len(s))
